"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.YOCTO = exports.ZEPTO = exports.ATTO = exports.FEMTO = exports.PICO = exports.NANO = exports.MICRO = exports.MILLI = exports.CENTI = exports.DECI = exports.DEKA = exports.HECTO = exports.KILO = exports.MEGA = exports.GIGA = exports.TERA = exports.PETA = exports.EXA = exports.ZETTA = exports.YOTTA = void 0;
exports.YOTTA = 'yotta';
exports.ZETTA = 'zetta';
exports.EXA = 'exa';
exports.PETA = 'peta';
exports.TERA = 'tera';
exports.GIGA = 'giga';
exports.MEGA = 'mega';
exports.KILO = 'kilo';
exports.HECTO = 'hecto';
exports.DEKA = 'deka';
exports.DECI = 'deci';
exports.CENTI = 'centi';
exports.MILLI = 'milli';
exports.MICRO = 'micro';
exports.NANO = 'nano';
exports.PICO = 'pico';
exports.FEMTO = 'femto';
exports.ATTO = 'atto';
exports.ZEPTO = 'zepto';
exports.YOCTO = 'yocto';
