"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.YOCTO = exports.ZEPTO = exports.ATTO = exports.FEMTO = exports.PICO = exports.NANO = exports.MICRO = exports.MILLI = exports.CENTI = exports.DECI = exports.DEKA = exports.HECTO = exports.KILO = exports.MEGA = exports.GIGA = exports.TERA = exports.PETA = exports.EXA = exports.ZETTA = exports.YOTTA = void 0;
exports.YOTTA = Math.pow(10, 24);
exports.ZETTA = Math.pow(10, 21);
exports.EXA = Math.pow(10, 18);
exports.PETA = Math.pow(10, 15);
exports.TERA = Math.pow(10, 12);
exports.GIGA = Math.pow(10, 9);
exports.MEGA = Math.pow(10, 6);
exports.KILO = Math.pow(10, 3);
exports.HECTO = Math.pow(10, 2);
exports.DEKA = Math.pow(10, 1);
exports.DECI = Math.pow(10, -1);
exports.CENTI = Math.pow(10, -2);
exports.MILLI = Math.pow(10, -3);
exports.MICRO = Math.pow(10, -6);
exports.NANO = Math.pow(10, -9);
exports.PICO = Math.pow(10, -12);
exports.FEMTO = Math.pow(10, -15);
exports.ATTO = Math.pow(10, -18);
exports.ZEPTO = Math.pow(10, -21);
exports.YOCTO = Math.pow(10, -24);
