export declare const ARRAY_TYPE = "array";
export declare const BOOLEAN_TYPE = "boolean";
export declare const INTEGER_TYPE = "integer";
export declare const NULL_TYPE = "null";
export declare const NUMBER_TYPE = "number";
export declare const STRING_TYPE = "string";
export declare const OBJECT_TYPE = "object";
export declare const NUMBER_OR_STRING_TYPE: string[];
export declare const STRING_OR_NUMBER_TYPE: string[];
export declare type ArrayType = typeof ARRAY_TYPE;
export declare type BooleanType = typeof BOOLEAN_TYPE;
export declare type IntegerType = typeof INTEGER_TYPE;
export declare type NullType = typeof NULL_TYPE;
export declare type NumberOrStringType = typeof NUMBER_OR_STRING_TYPE | typeof STRING_OR_NUMBER_TYPE;
export declare type NumberType = typeof NUMBER_TYPE;
export declare type ObjectType = typeof OBJECT_TYPE;
export declare type StringType = typeof STRING_TYPE;
export declare const TYPES: readonly ["array", "boolean", "integer", "null", "number", string[], "string", string[], "object"];
export declare type Type = typeof TYPES[number];
